name: expense
version: "3.8"
networks:
  default:
    name: expense
volumes:
  mysql:
services:
  mysql:
    # image: mysql:1.0.0
    image: charan466/mysql:1.0.0
    container_name: mysql # -- name mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ExpenseApp@1
      - MYSQL_USER=expense
      - MYSQL_PASSWORD=ExpenseApp@1
      - MYSQL_DATABASE=transactions
    volumes:
      - source: mysql # - mysql1:/var/lib/mysql 
        target: /var/lib/mysql
        type: volume # -v <volume-name>:/path/in/container

  # mysql:
  #   image: mysql:1.0.0
  #   container_name: mysql1 # -- name mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=ExpenseApp@1
  #     - MYSQL_USER=expense
  #     - MYSQL_PASSWORD=ExpenseApp@1
  #     - MYSQL_DATABASE=transactions
  #   volumes:
  #     - mysql1:/var/lib/mysql # -v <volume-name>:/path/in/container
      
  backend:
    # image: backend:1.0.0
    image: charan466/backend:1.0.0
    container_name: backend # -- name backend
    command: sh -c "sleep 20  && node /opt/server/index.js"
    depends_on:
      - mysql
  frontend:
    # image: frontend:1.0.0
    image: charan466/frontend:1.0.0
    container_name: frontend # -- name frontend
    depends_on:
      - backend
    ports:
      - "80:80"