name: expense
version: "3.8"
networks:
  default:
    name: expense
volumes:
  mysql: # docker volume create mysql
services:
  mysql:
    image: mysql:v1.0.0
    container_name: mysql1 # --name mysql
    volumes:
    - mysql:/var/lib/mysql # -v volume-name:/path-in-container
  
  # mysql:
  # image: mysql:v1.0.0
  # # image: charan466/mysql:1.0.0
  # container_name: mysql1 # -- name mysql
  # volumes:
  #   - source: mysql # - mysql1:/var/lib/mysql 
  #     target: /var/lib/mysql
  #     type: volume # -v <volume-name>:/path/in/container

  backend:
    image: backend:v1.0.0
    container_name: backend # --name backend
    command: sh -c "sleep 20  && node /opt/server/index.js"
    depends_on:
      - mysql
      
  frontend:
    image: frontend:v1.0.0
    container_name: frontend # --name frontend
    depends_on:
      - backend
    ports:
    - "80:80"

    